name: agalinec20_docker_compose

services:
  tvrtka:
    image: tvrtka_agalinec20
    container_name: tvrtka_agalinec20
    hostname: tvrtka_agalinec20
    build:
      context: ./agalinec20_vjezba_08_dz_3_tvrtka
      dockerfile: Dockerfile
    networks:
      mreza_agalinec20:
        ipv4_address: 20.24.5.2
    volumes:
      - svezak_agalinec20:/usr/app/podaci
    working_dir: /usr/app/podaci
    restart: unless-stopped

  partner:
    image: partner_agalinec20
    container_name: partner_agalinec20
    hostname: partner_agalinec20
    build:
      context: ./agalinec20_vjezba_08_dz_3_partner
      dockerfile: Dockerfile
    networks:
      mreza_agalinec20:
        ipv4_address: 20.24.5.3
    volumes:
      - svezak_agalinec20:/usr/app/podaci
    working_dir: /usr/app/podaci
    depends_on:
      - tvrtka
    restart: unless-stopped

  servisi:
    image: servis_agalinec20
    container_name: servis_agalinec20
    hostname: servis_agalinec20
    build:
      context: ./agalinec20_vjezba_08_dz_3_servisi
      dockerfile: Dockerfile
    networks:
      mreza_agalinec20:
        ipv4_address: 20.24.5.20
    restart: unless-stopped

volumes:
  svezak_agalinec20:
    external: true

networks:
  mreza_agalinec20:
    external: true
